### ISSUE TITLE
What's the correct way to use this mock library?

### ISSUE THREAD

**Issue by bkda** [Byron/yup-hyper-mock#14]
e.g.

> fn get_node_name(&self) -> String{
>         let node_name = self.get("http://foo.com/node");
>         node_name
> }

How can I mock `self.get()` method? Could you give more comprehensive document or usage to mock some method which uses hyper to send a request? Need your help, many thanks.

**Comment by Byron** [comment]
Actually I don't know that myself anymore, as the last time I used it was when I first created it. If I wanted to learn it now, I would have a look at the tests. They surely make clear how the common use cases look like.
I am closing this issue, but please feel free adding comments or reopen it as you see fit.
