### ISSUE TITLE
Cargo audit advisory: migrate `net2` to `socket2` crate

### ISSUE THREAD

**Issue by fussybeaver** [Byron/yup-hyper-mock#22]
I get this cargo audit problem when I include `yup-hyper-mock`:

```
$ cargo audit --deny warnings
Crate:         net2
Version:       0.2.37
Warning:       unmaintained
Title:         `net2` crate has been deprecated; use `socket2` instead
Date:          2020-05-01
ID:            RUSTSEC-2020-0016
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree:
net2 0.2.37
├── miow 0.2.2
│   └── mio 0.6.23
└── mio 0.6.23
```

https://crates.io/crates/cargo-audit

~Is there any interest in migrating to the `socket2` crate ?~
Edit: guessing that updating the mio dependency would eliminate this.

**Comment by Byron** [comment]
Thanks for letting me know! Is this something you could try?

Any help is appreciated. Thank you.
