### ISSUE TITLE
Hyper 1.x upgrade

### ISSUE THREAD

**Issue by fussybeaver** [Byron/yup-hyper-mock#24]
Is there any ongoing work to upgrade this crate to support the recent release of [Hyper 1.x](https://github.com/hyperium/hyper/releases), or is there any appetite to receive PR's in that regard ?

I haven't made any headway into this yet, but identified that it would be needed to update [Bollard](https://github.com/fussybeaver/bollard), which I'm currently working on.

**Comment by Byron** [comment]
Thanks for reporting!

I'd definitely love to see a PR for this to keep this crate relevant. It's very old and lives through contributions alone.
Thanks for offering to help!
